title: IT λ…ΈνΈ
description: "IT blog, build with Jekyll"
url: "http://devkhh.github.io"
author:
  name: "Kim H.H"
  email: "khh0929@naver.com"
  url: "http://devkhh.github.io"
  
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
